[package]
name = "liting"
version = "0.0.0"
authors = ["liting-yes <luz.liting@gmail.com>"]
edition = "2021"
description = "A cli tool for improve efficiency"
readme = "README.md"
keywords = ["cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
inquire = "0.7.4"
